services:
  - type: web
    name: chat_with_003_OpenRouter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chat_with_003.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
